config:
  name: "registration_icp"
  main_camera: 1
  origin_marker_id: 0
  origin_to_camera_file_pattern: "/media/frieder/System/data/inm_ba/registration_shm/cn{0:02d}/world2camera.json"
  origin_to_marker_file: "/home/frieder/data/origin_to_marker.json"
  add_single_windows: True
  dataflow:
    buffer_size: 3
    sensor_frequency: 30
    max_offset: 7
    cpu_count: 0
  cameras:
    - 1
    - 2
  marker_tracker:
    pattern: "ApriltagTracker"
    marker:
      marker_0:
          marker_id: 0
          marker_size: 0.131
  

  marker_tracker_aruco:
    pattern: "OpenCvArucoTracker"
    dictionary: "DICT_4X4_50"
    marker:
      marker_0:
        marker_id: 0
        marker_size: 0.19
      marker_1:
        marker_id: 1
        marker_size: 0.19
      marker_2:
        marker_id: 2
        marker_size: 0.19
      marker_3:
        marker_id: 3
        marker_size: 0.19
      marker_4:
        marker_id: 4
        marker_size: 0.19
      marker_5:
        marker_id: 5
        marker_size: 0.19
      marker_6:
        marker_id: 6
        marker_size: 0.19
  marker_tracker_fractal:
    pattern: "ArucoFractalTracker"
    marker_config: "FRACTAL_2L_6"
    marker_size: 0.131

  video_files:
    video_file_pattern: "/home/frieder/data/recording_rtw_calib/cn{0:02d}/k4a_capture.mkv"
    video_file_pattern2: "/home/frieder/data/recording_20220701/cn{0:02d}/capture_cn{0:02d}.mkv"

  shm_stream:
    image_stream: "camera_x5_shm"

  camera_stream:
    cameras:
      camera_0:
        DeviceID: "000090501412"
        HardwareSyncMode: "MASTER"
        SubordinateDelayOffMaster_usec: 0
        DepthDelayOffColor_usec: 0
        SyncedImagesOnly: True
        DepthMode: "WFOV_UNBINNED"
        FrameRate: 15
        ColorImageFormat: "COLOR_BGRA32"
        ColorResolution: "1440P"
      camera_1:
        DeviceID: "000084201412"
        HardwareSyncMode: "SUBORDINATE"
        SubordinateDelayOffMaster_usec: 120
        DepthDelayOffColor_usec: 0
        SyncedImagesOnly: True
        DepthMode: "WFOV_UNBINNED"
        FrameRate: 15
        ColorImageFormat: "COLOR_BGRA32"
        ColorResolution: "1440P"



